name: 02 Mensaje Personalizado

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  mensaje-personalizado:
    runs-on: ubuntu-latest
    steps:
      - name: Mensaje script a variable de entorno
        run: echo "Hello, ${{ vars.MY_NAME }}!"

