name: 08 Branch Deploy protected

on:
  push:
    branches:
      - master
      - release/*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: GHA_PROD
    steps:
      - name: Variable en produccion
        run: |
          echo "Tienda: ${{ vars.NAME_TEMP }}"
      
      - name: Secreto en produccion
        run: |
          echo "Pass: ${{ secrets.PASS_TEMP }}"
      

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name: despliegue
        run: echo "Desplegando en AWS..." 